Develop
borisbbtest/java-filmorate pull request #2
Opened 2024-12-15 10:48 UTC by borisbbtest

2024-12-15 11:04 UTC, borisbbtest commented
Я правильно понимаю , что тесты скрипта постамана , можно забить / Ибо там есть ручки которых не было в ТЗ А также описанной логике . ?

2024-12-16 04:41 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/controller/GlobalExceptionHandler.java
> +@ControllerAdvice
Отлично что использовал глобальный обработчик ошибок. Будет рассказываться чуть дальше на курсе.

2024-12-16 04:42 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/controller/GlobalExceptionHandler.java
> +        return new ResponseEntity<>(ex.getMessage(), HttpStatus.INTERNAL_SERVER_ERROR);
Т.к. это ошибка валидации, то лучше использовать BAD_REQUEST статус.

2024-12-16 04:44 UTC, VadimZharkov requested changes
Нужно поправить один момент со статусом. См коммент выше

2024-12-16 04:47 UTC, borisbbtest commented on src/main/java/ru/yandex/practicum/filmorate/controller/GlobalExceptionHandler.java
> +        return new ResponseEntity<>(ex.getMessage(), HttpStatus.INTERNAL_SERVER_ERROR);
Поправил

2024-12-16 04:49 UTC, borisbbtest commented on src/main/java/ru/yandex/practicum/filmorate/controller/GlobalExceptionHandler.java
> +        return new ResponseEntity<>(ex.getMessage(), HttpStatus.INTERNAL_SERVER_ERROR);
@VadimZharkov UP

2024-12-16 09:17 UTC, VadimZharkov approved these changes

2024-12-16 09:46 UTC, merged